#!/bin/bash

case $(uname) in
CYGWIN*) ;;
*) echo "can only be run on Cygwin" 1>&2; exit 1
esac

ProgPath=$(dirname "$0")
if [[ $# -eq 0 ]]; then
    tests=("$ProgPath/t/")
else
    tests=${@/#/"$ProgPath/t/"}
fi
PYTHONPATH="$ProgPath" "$ProgPath/simpletap.py" "${tests[@]}"
