#!/usr/bin/python

from winfstest import *

name = uniqname()

expect(0, "CreateDirectory %s 0" % name)
expect(0, "CreateFile %s\\foo GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" % name)
expect(0, "CreateFile %s\\baz GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" % name)
expect(0, "MoveFileEx %s\\foo %s\\bar 0" % (name, name))
expect("ERROR_FILE_NOT_FOUND", "GetFileInformation %s\\foo" % name)
expect(0, "GetFileInformation %s\\bar" % name)
expect("ERROR_ALREADY_EXISTS", "MoveFileEx %s\\bar %s\\baz 0" % (name, name))
expect(0, "GetFileInformation %s\\bar" % name)
expect(0, "GetFileInformation %s\\baz" % name)
expect(0, "MoveFileEx %s\\bar %s\\baz MOVEFILE_REPLACE_EXISTING" % (name, name))
expect("ERROR_FILE_NOT_FOUND", "GetFileInformation %s\\bar" % name)
expect(0, "GetFileInformation %s\\baz" % name)
expect(0, "DeleteFile %s\\baz" % name)
expect(0, "RemoveDirectory %s" % name)

expect(0, "CreateDirectory %s 0" % name)
expect(0, "CreateDirectory %s\\foo 0" % name)
expect(0, "CreateDirectory %s\\baz 0" % name)
expect(0, "MoveFileEx %s\\foo %s\\bar 0" % (name, name))
expect("ERROR_FILE_NOT_FOUND", "GetFileInformation %s\\foo" % name)
expect(0, "GetFileInformation %s\\bar" % name)
expect("ERROR_ALREADY_EXISTS", "MoveFileEx %s\\bar %s\\baz 0" % (name, name))
expect(0, "GetFileInformation %s\\bar" % name)
expect(0, "GetFileInformation %s\\baz" % name)
expect("ERROR_ACCESS_DENIED", "MoveFileEx %s\\bar %s\\baz MOVEFILE_REPLACE_EXISTING" % (name, name))
expect(0, "GetFileInformation %s\\bar" % name)
expect(0, "GetFileInformation %s\\baz" % name)
expect(0, "RemoveDirectory %s\\bar" % name)
expect(0, "RemoveDirectory %s\\baz" % name)
expect(0, "RemoveDirectory %s" % name)

expect(0, "CreateDirectory %s 0" % name)
expect(0, "CreateDirectory %s\\foo 0" % name)
expect(0, "CreateDirectory %s\\bar 0" % name)
expect(0, "CreateFile %s\\foo\\hello GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" % name)
expect(0, "MoveFileEx %s\\foo\\hello %s\\bar\\world 0" % (name, name))
expect("ERROR_FILE_NOT_FOUND", "GetFileInformation %s\\foo\\hello" % name)
expect(0, "GetFileInformation %s\\bar\\world" % name)
expect(0, "DeleteFile %s\\bar\\world" % name)
expect(0, "RemoveDirectory %s\\bar" % name)
expect(0, "RemoveDirectory %s\\foo" % name)
expect(0, "RemoveDirectory %s" % name)

testdone()
